server.port: 8080

spring:
  application:
    name: billionaire

  config:
    import: "aws-parameterstore:"

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
